### ISSUE TITLE
Still being developed?

### ISSUE THREAD

**Issue by braunsonm** [niallthomson/terraform-provider-k14s#1]
Hey @niallthomson  I'm much more interested in your version here... the official carvel one seems somewhat abandoned and has some bugs. I also think how you designed it to not require the binaries is a better design overall.

Are you still working on this project or not anymore? I noticed it still uses the old name (k14s)

**Comment by niallthomson** [comment]
Hi @braunsonm , I don't plan to work on this as I left VMware a couple years ago and I don't really use the carvel tools now I'm out of the ecosystem.

**Comment by braunsonm** [comment]
Thanks for the honest answer! I may use your work to build something if you don't mind.

**Comment by niallthomson** [comment]
If this can be helpful then go for it!
